### ISSUE TITLE
clean quit on SDL window close

### ISSUE THREAD

**Issue by tehn** [ryleelyman/seamstress#42]
closing the main SDL window appears to quit seamstess but leave the terminal in a broken state with character echo turned off, requiring a term reset. this might be a matter of ncurses not deinitializing properly?

might be reassuring to have a final shutdown/goodbye message to know we've exited cleanly

**Comment by tehn** [comment]
ah, i'm a bad issue poster.

ubuntu, tilix, bash

**Comment by tehn** [comment]
same symptom when using menubar quit item

**Comment by robbielyman** [comment]
interesting, I can't reproduce with `kitty` and `Terminal.app` on macos, which is odd
