### ISSUE TITLE
`lib/lfo` calls unknown symbol `_menu`

### ISSUE THREAD

**Issue by p3r7** [ryleelyman/seamstress#59]
`lib/lfo` calls `_menu.rebuild_params()` ([here](https://github.com/ryleelyman/seamstress/blob/0f1bb7bacc7f5c011af37067b52c07394dbdc22a/lua/lib/lfo.lua#L191) and [here](https://github.com/ryleelyman/seamstress/blob/0f1bb7bacc7f5c011af37067b52c07394dbdc22a/lua/lib/lfo.lua#L550)).

but in seamstress the `_menu` global is called `paramsMenu` ([source](https://github.com/ryleelyman/seamstress/blob/0f1bb7bacc7f5c011af37067b52c07394dbdc22a/lua/core/seamstress.lua#L20)).

i'd have been happy to fix but don't know which approach to take.

possible choices:
- quick'n'dirty: replace `_menu` with `paramsMenu` in `lib/lfo` 
- 🙈-patch: alias globally `_menu` to `paramsMenu` in `seamstress.lua`
- follow norns conventions: replace all occurrences of `paramsMenu` with `_menu`

**Comment by robbielyman** [comment]
hmmmm. I like `_menu = paramsMenu` in `seamstress.lua`. I don't at the moment see room for other menus on the params window, but this seems the most reasonable for future changes.
