### ISSUE TITLE
blank param window on Linux (on v1.0.5)

### ISSUE THREAD

**Issue by p3r7** [ryleelyman/seamstress#89]
hey hey!

i haven't updated for a while. i just grabbed the latest version and the param window is now smaller (good) but also very blank (only a black bg).

i also get this (potentially unrelated) error upon closing:

```
> X Error of failed request:  GLXBadContextTag
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  68556
  Current serial number in output stream:  68556
```

**Comment by p3r7** [comment]
~~mhm, so apparently the blank params window also means borked initial params state.~~

~~trying to `params:add_*` results in:~~

```
/usr/local/share/seamstress/lua/core/params.lua:460:` attempt to concatenate a nil value (local 'index')
```

nevermind, this one was on my side.

**Comment by robbielyman** [comment]
Can reproduce! I think somehow `screen.text()` is sad about multithreading on Linux... I'll take a crack at it soon

ETA: `screen.geometry` is also broken: looks like on Linux textures must be created on the same thread as the renderer, while macOS has no such restriction.
