### ISSUE TITLE
bug: `util.scandir` borked on OS X

### ISSUE THREAD

**Issue by p3r7** [ryleelyman/seamstress#96]
hey!

**the issue**

so `util.scandir` relies on `ls` to list files in a directory. but it uses the `--group-directories-first` option ([src](https://github.com/ryleelyman/seamstress/blob/main/lua/lib/util.lua#L42C31-L42C56)) to have directories listed before regular files in the output,. but this flag is only available for the GNU version of `ls` (OS X comes w/ BSD's version).

**paths of resolution**

i see 3 ways to fix this:
- drop the `--group-directories-first` flag (meh as we'd loose feature parity w/ norns)
- have `coreutils` be a dependency to seamstress on OS X and call `gls` instead of `ls`
- use an alternative method, such as successive calls to `find` ([per this rec](https://unix.stackexchange.com/a/22818))

2 & 3 both require to be able to test the current OS in the Lua layer. idk if seamstress exposes a global w/ that info already or if this is something that would need to be added.

also this fix would be back-ported to norns itself (for allowing to run `norns-desktop` on OS X, which is something that got discussed recently).

**Comment by robbielyman** [comment]
i don't really have a strong opinion here – i've never used `util.scandir` on norns or seamstress. i would like not to make seamstress depend on coreutils, although i suppose it's not onerous.

seamstress could definitely expose the current os itself, but calling `uname` is right there already...
